API_ENDPOINTS:
  login_check: https://passport.goofish.com/newlogin/hasLogin.do
  message_headinfo: https://h5api.m.goofish.com/h5/mtop.idle.trade.pc.message.headinfo/1.0/
  token: https://h5api.m.goofish.com/h5/mtop.taobao.idlemessage.pc.login.token/1.0/
APP_CONFIG:
  api_version: '1.0'
  app_key: 444e9908a51d1cb236a27862abc769c9
  app_version: '1.0'
  platform: web
AUTO_REPLY:
  api:
    enabled: false  # 禁用API回复，使用AI回复或关键词回复
    host: 0.0.0.0  # 绑定所有网络接口，支持IP访问
    port: 8080     # Web服务端口
    timeout: 10
    url: http://localhost:8080/xianyu/reply  # 修复URL地址
  default_message: 亲爱的"{send_user_name}" 老板你好！所有宝贝都可以拍，秒发货的哈~不满意的话可以直接申请退款哈~
  enabled: true
  max_retry: 3
  retry_interval: 5

# 增强AI回复配置
AI_REPLY:
  use_enhanced: true  # 启用增强AI回复引擎
  enhanced_features:
    context_aware: true  # 启用上下文感知对话
    multi_expert: true   # 启用多专家路由系统
    negotiation_tracking: true  # 启用议价轮次跟踪
    intent_detection: true  # 启用智能意图识别
  context_management:
    max_messages: 10     # 最多保留的对话消息数
    expire_time: 3600    # 上下文过期时间（秒）
  temperature_settings:
    price_intent: 0.3    # 价格咨询的温度参数
    technical_intent: 0.2  # 技术支持的温度参数
    general_intent: 0.5  # 一般咨询的温度参数
ITEM_DETAIL:
  auto_fetch:
    enabled: true  # 是否启用自动获取商品详情
    api_url: https://selfapi.zhinianboke.com/api/getItemDetail  # 外部API地址
    timeout: 30  # 请求超时时间（秒）
    max_concurrent: 3  # 最大并发请求数
    retry_delay: 0.5  # 请求间隔（秒）

# 增强商品信息管理配置
ITEM_MANAGEMENT:
  use_enhanced: true  # 启用增强商品信息管理器
  cache_settings:
    memory_cache_duration: 86400  # 内存缓存24小时（秒）
    database_cache_duration: 604800  # 数据库缓存7天（秒）
    auto_cleanup: true  # 自动清理过期缓存
  enhanced_features:
    full_detail_extraction: true  # 提取完整商品详情
    attribute_parsing: true  # 解析商品属性和标签
    seller_info_extraction: true  # 提取卖家信息
    location_info_extraction: true  # 提取地理位置信息
    image_info_extraction: true  # 提取图片信息
  api_integration:
    use_real_time_api: true  # 启用实时API获取
    fallback_to_database: true  # API失败时回退到数据库
    retry_count: 3  # API重试次数
    retry_delay: 1.0  # 重试间隔（秒）
COOKIES:
  last_update_time: ''
  value: ''
DEFAULT_HEADERS:
  accept: application/json
  accept-language: zh-CN,zh;q=0.9
  cache-control: no-cache
  origin: https://www.goofish.com
  pragma: no-cache
  priority: u=1, i
  referer: https://www.goofish.com/
  sec-ch-ua: '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"'
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: '"Windows"'
  sec-fetch-dest: empty
  sec-fetch-mode: cors
  sec-fetch-site: same-site
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/133.0.0.0 Safari/537.36
HEARTBEAT_INTERVAL: 15
HEARTBEAT_TIMEOUT: 5
LOG_CONFIG:
  compression: zip
  format: '<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level>
    | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
  level: INFO
  retention: 7 days
  rotation: 1 day
MANUAL_MODE:
  enabled: false
  timeout: 3600
  toggle_keywords: []
MESSAGE_EXPIRE_TIME: 300000
TOKEN_REFRESH_INTERVAL: 7200   # 2小时刷新一次Token，减少过期风险
TOKEN_RETRY_INTERVAL: 600     # Token刷新失败后10分钟重试
WEBSOCKET_HEADERS:
  Accept-Encoding: gzip, deflate, br, zstd
  Accept-Language: zh-CN,zh;q=0.9
  Cache-Control: no-cache
  Connection: Upgrade
  Host: wss-goofish.dingtalk.com
  Origin: https://www.goofish.com
  Pragma: no-cache
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/133.0.0.0 Safari/537.36
WEBSOCKET_URL: wss://wss-goofish.dingtalk.com/
